type Stat = 'STR' | 'DEX' | 'CON' | 'INT' | 'SPD' | 'CHA' | 'LCK' | 'STRENGTH' | 'DEXTERITY' | 'CONSTITUTION' | 'INTELLIGENCE' | 'SPEED' | 'CHARISMA' | 'LUCK' | 'HP' | 'MP';
type Status =
    | 'Adrenaline'
    | 'All Stats Down'
    | 'All Stats Up'
    | 'Attraction'
    | 'Auto Revive'
    | 'Backflip'
    | 'Bleed'
    | 'Bleed Thorns'
    | 'Blessing of Peace'
    | 'Blind'
    | 'Body Guard'
    | 'Bonus Attack'
    | 'Bonus Move'
    | 'Bonus Range'
    | 'Bounty'
    | 'Brace'
    | 'Brittle'
    | 'Broken'
    | 'Bruise'
    | 'Burn'
    | 'Captured Familiar'
    | 'Charge'
    | 'Charisma Down'
    | 'Charisma Up'
    | 'Charmed'
    | 'Cleave'
    | 'Confusion'
    | 'Constitution Down'
    | 'Constitution Up'
    | 'Counter Attack'
    | 'Crit Chance Up'
    | 'Cure Random Injury'
    | 'Cursed'
    | 'Damage Down'
    | 'Damage Up'
    | 'Delayed Pain'
    | 'Dexterity Down'
    | 'Dexterity Up'
    | 'Dodge Chance'
    | 'Doomed'
    | 'Double Action'
    | 'Double Cast'
    | 'Drowsy'
    | 'Empty Mind'
    | 'Energized'
    | 'Entangled'
    | 'Exhaustion'
    | 'Extra Attacks'
    | 'Fear'
    | 'Flammable'
    | 'Flying'
    | 'Fragile'
    | 'Freeze'
    | 'Free Spell'
    | 'Grappled'
    | 'Health Regen (Diminishing)'
    | 'Health Regen'
    | 'Heat Wave'
    | 'Heavy Hits'
    | 'Hex'
    | 'Holy Shield'
    | 'Immobile'
    | 'Infested'
    | 'Initiative Down'
    | 'Initiative Up'
    | 'Insight'
    | 'Intelligence Down'
    | 'Intelligence Up'
    | 'Kinetic Spikes'
    | 'Leeches'
    | 'Lifesteal'
    | 'Luck Down'
    | 'Luck Up'
    | 'Madness'
    | 'Magic Damage Up'
    | 'Magic Weakness'
    | 'Mana Leeches'
    | 'Marked'
    | 'Meaty'
    | 'Metal'
    | 'Miss Chance'
    | 'Movement Down'
    | 'Movement Up'
    | 'Muted'
    | 'No Health Regen'
    | 'No Mana Regen'
    | 'Ostracized'
    | 'Petrify'
    | 'Poisonous'
    | 'Poison'
    | 'Poison Lace'
    | 'Poison Lace Weapon'
    | 'Possessed'
    | 'Preemptive Counter'
    | 'Probed'
    | 'Random Injury'
    | 'Range Up'
    | 'Reflect'
    | 'RELOAD'
    | 'Rot'
    | 'Scrambled'
    | 'Sentry Mode'
    | 'Serrated Claws'
    | 'Shield'
    | 'Short Circuit'
    | 'Sleep'
    | 'Slow'
    | 'Soul Link'
    | 'Sparkle'
    | 'Speed Down'
    | 'Speed Up'
    | 'Stat Bounty'
    | 'Stealth'
    | 'Strength Down'
    | 'Strength Up'
    | 'Stun'
    | 'Tarred'
    | 'Tech'
    | 'The Alpha'
    | 'Thorns'
    | 'Trample'
    | 'Transformation'
    | 'Weakness'
    | 'Webbed'
    | 'Wet'
    | 'Worn'
    | 'Zombie';
type Collar = 'COLLARLESS' | 'FIGHTER' | 'HUNTER' | 'MAGE' | 'TANK' | 'CLERIC' | 'THIEF' | 'NECROMANCER' | 'TINKERER' | 'BUTCHER' | 'DRUID' | 'PSYCHIC' | 'MONK' | 'JESTER';

export type { Stat, Status, Collar };
